### ISSUE TITLE
mesh issue on downloading ortho4xp1.20b

### ISSUE THREAD

**Issue by patrick75008** [oscarpilote/Ortho4XP#100]
I cannot download the tiles mesh,
  dont' understand what is the issue there

Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2751, in build_mesh
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2156, in load_altitude_matrix
FileNotFoundError: [Errno 2] No such file or directory: '..\\tmp\\M31.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 5233, in build_tile_list
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2753, in build_mesh
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2156, in load_altitude_matrix
FileNotFoundError: [Errno 2] No such file or directory: '..\\tmp\\M31.zip'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2751, in build_mesh
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2156, in load_altitude_matrix
FileNotFoundError: [Errno 2] No such file or directory: '..\\tmp\\M31.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2753, in build_mesh
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2156, in load_altitude_matrix
FileNotFoundError: [Errno 2] No such file or directory: '..\\tmp\\M31.zip'

any idea ??
thk you

**Comment by patrick75008** [comment]
Its happened when Just installed Ortho4xp under Windows 10 with Oortho4XP.7 z

Start program  "python3 Ortho4xp_v120b.py"

Main window comes up and select Base source - GO2 Zoom level 17 also check "Custom overlay dir:" and select X-Plane 11/Global Scenery

Click on "Earth tile map" and "Tiles collection" window comes up

I am able to move around  the map and select 5 tiles near Paris France

Then I check boxes "Build masks" and "Build overlays"

The processing starts when I click on "Batch Build"

Step 1 for tile 1 completes but step 2 "Building mesh for tile +39-077" produces the following error messages on my terminal window:

then this is the panel's message 


Tile 1 / 5

Step 1 : Building OSM and patch data for tile +47+002 : 
--------

-> Downloading airport and water/ground boundary data from Openstreetmap :
    Obtaining OSM data for way["aeroway"="aerodrome"]
     Done.
     A total of 362 node(s) and 10 way(s).
       * LFEH Aérodrome d'Aubigny-sur-Nère
       *      Aérodrome de La Cave
       *      Aérodrome de Cosseneux Vouzon
       * LFEM Aérodrome de Montargis - Vimory
       * LFGH Aérodrome de Cosne-sur-Loire
       * LFFV Aérodrome de Vierzon Méreau
       * LFLD Aéroport de Bourges
       * LFOZ Aéroport du Loiret - Orléans - Saint-Denis-de-l'Hôtel
       * LFEI Aérodrome de Briare-Châtillon
       * LFOA Base aérienne 702 Avord
    Obtaining OSM data for rel["aeroway"="aerodrome"]
     Done.
     A total of 0 node(s) and 0 relation(s).
    Obtaining OSM data for way["aeroway"="heliport"]
     Done.
     A total of 0 node(s) and 0 way(s).
    Obtaining OSM data for way["natural"="water"]["tidal"!="yes"]
     Done.
     A total of 188614 node(s) and 10115 way(s).
    Obtaining OSM data for rel["natural"="water"]["tidal"!="yes"]
     Done.
     A total of 27597 node(s) and 450 relation(s).
    Obtaining OSM data for way["waterway"="riverbank"]
     Done.
     A total of 22548 node(s) and 299 way(s).
    Obtaining OSM data for rel["waterway"="riverbank"]
     Done.
     A total of 12135 node(s) and 25 relation(s).
    Obtaining OSM data for way["natural"="coastline"]
     Done.
     A total of 0 node(s) and 0 way(s).
    Obtaining OSM data for way["waterway"="dock"]
     Done.
     A total of 9 node(s) and 1 way(s).
   -> process of the associated data completed : 114985 new nodes.
-> Cutting off of too long edges,
-> Adding patch data for the mesh, 
-> Adding of edges related to the orthophoto grid and computation of
     their intersections with OSM edges,
     Removal of obsolete edges,
     Removal of obsolete nodes,
-> Transcription of the updated data to the file ..\Tiles\zOrtho4XP_+47+002\Data+47+002.poly
   Remain 164167 edges in total.

Completed in 73.81sec.
_________________________________________________________________________________________________

Tile 1 / 5

Step 2 : Building mesh for tile +47+002 : 
--------

-> Loading of elevation data.
   No elevation file found, I download it from viewfinderpanorama (J. de Ferranti)
   Done. The zip archive will now be extracted in the Elevation_data dir.
   No elevation file found, I download it from viewfinderpanorama (J. de Ferranti)
   Done. The zip archive will now be extracted in the Elevation_data dir.

**Comment by patrick75008** [comment]
python feedback :
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2751, in build_mesh
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2156, in load_altitude_matrix
FileNotFoundError: [Errno 2] No such file or directory: '..\\tmp\\L31.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 5233, in build_tile_list
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2753, in build_mesh
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2156, in load_altitude_matrix
FileNotFoundError: [Errno 2] No such file or directory: '..\\tmp\\L31.zip'

**Comment by d41k4n** [comment]
You are running an outdated version. Try installing 1.30 from the latest master branch.

**Comment by patrick75008** [comment]
Thk you very much
I will do it.
Bes regards
Patrick

**Comment by patrick75008** [comment]
THK YOU VERY MUCH OSCAR I did do the job and it works perfectly. Your Ortho4xP is a awesome application ! the you for this very impressive work.

The YOUTUBE tutorial from 505Northman did help me very much to enter the python mysteries… not simple for non software/programers/ engineers like me !!

Excellent job indeed.

Best regards, 
Patrick Teboul
Paris, France.
