### ISSUE TITLE
I am seeing new 'python???' errors in Terminal

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#101]
Things were working fine until yesterday.  Ortho appears to be working fine and I do not see any error messages in the program. However, after it completes a scenery process, there is no added scenery file folders in Custom Scenery.
However in Terminal, I am seeing this;
THIS has been showing up for a while and is repeated numerous times>>>>>
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/crs.py:77: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))

NOW I am seeing this type of message, 

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "./src/O4_Parallel_Utils.py", line 18, in run
    self._success[0]= self._task(*args) and self._success[0] 
  File "./src/O4_Mask_Utils.py", line 311, in build_mask
    blur_width=[L/pxscal for L in tile.masks_width]
TypeError: 'int' object is not iterable

****IT CONTINUES FOR SEVERAL THREAD MESSAGES**.** 

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "./src/O4_Parallel_Utils.py", line 18, in run
    self._success[0]= self._task(*args) and self._success[0] 
  File "./src/O4_Mask_Utils.py", line 311, in build_mask
    blur_width=[L/pxscal for L in tile.masks_width]
TypeError: 'int' object is not iterable

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

**Comment by d41k4n** [comment]
You've selected masking mode "3steps" but only provided a single value for masks_width. Make sure you read the hint text an check your config settings.
