### ISSUE TITLE
MemoryError crash

### ISSUE THREAD

**Issue by njanke96** [oscarpilote/Ortho4XP#121]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File ".\src\O4_Tile_Utils.py", line 158, in build_tile_list
    VMAP.build_poly_file(tile)
  File ".\src\O4_Vector_Map.py", line 60, in build_poly_file
    include_water(vector_map,tile)
  File ".\src\O4_Vector_Map.py", line 303, in include_water
    if not OSM.OSM_queries_to_OSM_layer(queries,water_layer,tile.lat,tile.lon,tags_of_interest,cached_suffix='water'):
  File ".\src\O4_OSM_Utils.py", line 306, in OSM_queries_to_OSM_layer
    osm_layer.update_dicosm(response,input_tags,target_tags)
  File ".\src\O4_OSM_Utils.py", line 66, in update_dicosm
    pfile=io.StringIO(osm_input.decode(encoding="utf-8"))
MemoryError
```

This halts my batch build process on pretty much any tile. I have 16GB of RAM. Using v1.30

**Comment by njanke96** [comment]
Switching to 64 bit python fixed the error, I wont close this in case a dev still considers the app using so much memory to be an issue.

**Comment by d41k4n** [comment]
Memory usage depends on OSM data. So this is normal/expected in some cases and using the 64 bit Python runtime is recommended anyway.
