### ISSUE TITLE
Running the Ortho script with Python Launcher.

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#129]
I am trying to make get the script to run with a double click, macOS.
Python 3.8.3 just came out and we are getting closer.  

https://bugs.python.org/msg368819

The Python Launcher comes up and then stops because of an error.  I do not get this error when running the Ortho script from the Terminal nor when setting it up to run using IDLE with a double click. I have not gotten an error when testing other little python scripts and double click. 

The Terminal session is:

**Last login: Thu May 14 08:12:17 on ttys000
cd '/Volumes/BigHDD/Ortho4XP-master/' && '/usr/bin/pythonw'  '/Volumes/BigHDD/Ortho4XP-master/Ortho4XP_v130.py'  && echo Exit status: $? && exit 1
But what do I know? % cd '/Volumes/BigHDD/Ortho4XP-master/' && '/usr/bin/pythonw'  '/Volumes/BigHDD/Ortho4XP-master/Ortho4XP_v130.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Volumes/BigHDD/Ortho4XP-master/Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 597
SyntaxError: Non-ASCII character '\xc2' in file ./src/O4_Imagery_Utils.py on line 597, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
But what do I know? %**

**Comment by OldSubSailor** [comment]
As an additional comment, everything works as expected when running the Ortho script via double click IDLE. Except that I get a listing of error messages when Extracting Overlays.  It does not seem to impact Ortho4XP and does not appear when running from the Terminal.

**Comment by OldSubSailor** [comment]
The fix for this is in editing the Python Launcher preferences.
Per Ned Deily at python bug tracker

you will need to change the Interpreter setting in the Launcher Preferences panel.  In the box that says "/usr/bin/pythonw", type "/usr/local/bin/python3"; that setting will then be remembered on subsequent launches.
