### ISSUE TITLE
Linux geotiff error - missing gdal_translate

### ISSUE THREAD

**Issue by Jannomag** [oscarpilote/Ortho4XP#139]
Hi,
I can't get Making Geotiffs working. I'm getting following error:
```Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./src/O4_Imagery_Utils.py", line 1105, in build_geotiffs
    convert_texture(tile,til_x_left,til_y_top,zoomlevel,provider_code,type='tif')
  File "./src/O4_Imagery_Utils.py", line 1435, in convert_texture
    if not subprocess.call(conv_cmd,stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT):
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gdal_translate'
```

I followed the installation manual. 
Ubuntu 20.04 with Python 3.8.2

**Comment by Jannomag** [comment]
nvm - found the solution by following [this site](https://mothergeo-py.readthedocs.io/en/latest/development/how-to/gdal-ubuntu-pkg.html).
Key to sultion was to set the path for gdal with this:
```export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal```

May the devs add this to the installation manual?
