### ISSUE TITLE
Ouch - Attempted re-install on MacOS killed my Ortho4XP

### ISSUE THREAD

**Issue by slowrunner** [oscarpilote/Ortho4XP#181]
Four years ago I successfully installed Ortho4XP and it was running well at that time.

In the process of creating a clean X-Plane11.55 with a recent Ortho4XP installation, following the Install_Instructions.txt and running install_mac.sh, python3 Ortho4XP_v130.py now generates the following fatal error:
```
python3 Ortho4XP_v130.py 
Traceback (most recent call last):
  File "Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 28, in <module>
    import O4_Vector_Utils as VECT
  File "./src/O4_Vector_Utils.py", line 3, in <module>
    from shapely import geometry, affinity
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shapely/geometry/base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shapely/geos.py", line 113, in <module>
    free = load_dll('c').free
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
```

Suggestions to get it working again?

OS: macOS Monterey 12.4
System: Mac mini (2018)  
Processor: 3.2GHz 6-core Intel Core i7
Memory: 32GB

**Comment by slowrunner** [comment]
I believe the issue heralds from

- brew installing Python3.9 and
- commandlinetools/MacOS installs Python3.8 and
- python3 is linked to Python3.8, so when
- install_mac.os runs it installs stuff to Python3.9 site packages,
- but running python3 Ortho4XP_v140.py will use Python3.8
which does not have the dependencies installed.

 Not sure what to recommend to anyone else.

The last commands I executed before it started working:

- softwareupdate --all --install --force
- brew link --overwrite python@3.9
- brew reinstall tcl-tk
- echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
- brew doctor
- brew cleanup
- brew link jpeg
- brew link qt
- ./install_mac.sh
- brew install python-tk 
- python3 --version  (Python 3.9.13)
- python3 Ortho4XP_v130.py
