### ISSUE TITLE
Error using provider with a different projection then 4326

### ISSUE THREAD

**Issue by marcfsx** [oscarpilote/Ortho4XP#221]
Hi Oscar,

Good to see you back !

I found this issue with the latest (version 1.4).
I am using the provider PDOK20, using EPSG 3857.
The code has an issue with converting it to 4326.
I have tried different projections as well (for example: 28992) but the issue is the same.

I am using
Python 3.11.8
Pyproy  3.6.1
GDAL 3.8.2
Rtree 1.10
Shapely 2.0.2

Exception in thread Thread-3 (download_textures):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\FSXP3D\Ortho4XP-master_239\.\src\O4_Tile_Utils.py", line 29, in download_textures
    if IMG.build_jpeg_ortho(tile, *texture_attributes):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FSXP3D\Ortho4XP-master_239\.\src\O4_Imagery_Utils.py", line 1738, in build_jpeg_ortho
    if not download_jpeg_ortho(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\FSXP3D\Ortho4XP-master_239\.\src\O4_Imagery_Utils.py", line 1567, in download_jpeg_ortho
    [xmin, ymax] = GEO.geo_to_webm(lonmin, latmax)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Transformer' object is not callable

**Comment by marcfsx** [comment]
hi Oscar,
Resolved the issue myself.
Closed.
