### ISSUE TITLE
Water Mask creating error

### ISSUE THREAD

**Issue by emiliovfx** [oscarpilote/Ortho4XP#249]
Hello.  Great job with the update of ortho4XP for the new XP12 terrain format.

Most of the tiles I already converted from the old XP11 are working fine, except one, where an error is hanging the water mask creation process.

Here is the error.

```
Exception in thread Thread-7 (build_masks):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Ortho4XP-master\1.4\Ortho4XP-master\Ortho4XP-master\src\O4_Mask_Utils.py", line 119, in build_masks
    (dico_sea, dico_inland) = record_water_tris(tile, )
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Ortho4XP-master\1.4\Ortho4XP-master\Ortho4XP-master\src\O4_Mask_Utils.py", line 453, in record_water_tris
    pt_in[5 * i + 3 : 5 * i + 5] = [
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (0,) into shape (2,)
```

The mesh is looking good.

![image](https://github.com/oscarpilote/Ortho4XP/assets/68814463/e4f6d46a-7c58-42f4-90ee-a3b3229483d7)

Here is a link to download the generated mesh where the problem of creating the water masks is happening.

https://www.dropbox.com/scl/fi/krli5q5neo7hwj8xwql0g/zOrtho4XP_-17-102.zip?rlkey=nezw3f3s02iga5kob5mc2eo1p&dl=1

The water masks creation process in o4xp 1.3 is working well.

I hope this helps to debug this error.

**Comment by emiliovfx** [comment]
I found the issue.  It hangs when reading adjacent tiles info, probably when defining the border mask edges.

I removed the adjacent tiles and o4xp was able to generate the masks for the specific tile.
