### ISSUE TITLE
debian trixie: TypeError: 'MultiPolygon' object is not iterable

### ISSUE THREAD

**Issue by schenlap** [oscarpilote/Ortho4XP#279]
With debian trixie i get the following error during "Assemble Vector data"

```
  full_area=VECT.ensure_MultiPolygon(ops.cascaded_union([dico_airports[airport]['boundary'],dico_airports[airport]['runway'][0],dico_airports[airport]['hangar'],dico_airports[airport]['taxiway'][0],dico_airports[airport]['apron'][0]]))
Exception in thread Thread-1 (build_poly_file):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/steve/X-Plane 12/Ortho4XP-1.30/src/O4_Vector_Map.py", line 42, in build_poly_file
    (apt_array,apt_area)=include_airports(vector_map,tile) 
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/X-Plane 12/Ortho4XP-1.30/src/O4_Vector_Map.py", line 138, in include_airports
    APT.smooth_raster_over_airports(tile,dico_airports)
  File "/home/steve/X-Plane 12/Ortho4XP-1.30/src/O4_Airport_Utils.py", line 429, in smooth_raster_over_airports
    for polygon in full_area:
                   ^^^^^^^^^
TypeError: 'MultiPolygon' object is not iterable

```

Python 3.12.6

**Comment by schenlap** [comment]
i thought with https://github.com/oscarpilote/Ortho4XP/pull/186 it should be fixed?

**Comment by w8sl** [comment]
It should be:

for polygon in full_area.geoms

(See my 130 branch)
