### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by DemonRem** [oscarpilote/Ortho4XP#35]
E:\Github\Ortho4XP>Ortho4XP_v130.py
ERROR: Providers/O4_Custom_URL.py contains invalid code. The corresponding providers won't probably work.
Traceback (most recent call last):
  File "E:\Github\Ortho4XP\Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File ".\src\O4_Imagery_Utils.py", line 22, in <module>
    import O4_Vector_Utils as VECT
  File ".\src\O4_Vector_Utils.py", line 5, in <module>
    from rtree import index
  File "C:\Users\Nayla Hikari\AppData\Local\Programs\Python\Python36\lib\site-packages\rtree\__init__.py", line 1, in <module>
    from .index import Rtree
  File "C:\Users\Nayla Hikari\AppData\Local\Programs\Python\Python36\lib\site-packages\rtree\index.py", line 5, in <module>
    from . import core
  File "C:\Users\Nayla Hikari\AppData\Local\Programs\Python\Python36\lib\site-packages\rtree\core.py", line 116, in <module>
    raise OSError("could not find or load spatialindex_c.dll")
OSError: could not find or load spatialindex_c.dll

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/155224-error-within-providerso4_custom_urlpy/&do=findComment&comment=1467122

https://forums.x-plane.org/index.php?/forums/topic/153909-spatialindex_cdll-issue-with-ortho4xp_v130/&do=findComment&comment=1456491
