### ISSUE TITLE
MemoryError Ortho4XP 1.30 under Python 3.7

### ISSUE THREAD

**Issue by Raurits** [oscarpilote/Ortho4XP#46]
Just downloaded latest Ortho4XP 1.30 with Python 3.7, including the 37-versions of the libraries. Using Windows 10, latest. 

When trying to generate the first tiles, I am confronted with a MemoryError, which halts the generation process, see below. 

I note that during installation, I skipped installing Visual Studio Tools, because I was overwhelmed by the options and I did not know which ones to select. This is not a developer machine, but I might have installed something in the past. 

Suggestions are much appreciated. 

- Raurits

-----------------------------
D:\games\Ortho4XP-master>python Ortho4XP_v130.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Raurits\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Raurits\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File ".\src\O4_Tile_Utils.py", line 130, in build_all
    VMAP.build_poly_file(tile)
  File ".\src\O4_Vector_Map.py", line 60, in build_poly_file
    include_water(vector_map,tile)
  File ".\src\O4_Vector_Map.py", line 303, in include_water
    if not OSM.OSM_queries_to_OSM_layer(queries,water_layer,tile.lat,tile.lon,tags_of_interest,cached_suffix='water'):
  File ".\src\O4_OSM_Utils.py", line 306, in OSM_queries_to_OSM_layer
    osm_layer.update_dicosm(response,input_tags,target_tags)
  File ".\src\O4_OSM_Utils.py", line 66, in update_dicosm
    pfile=io.StringIO(osm_input.decode(encoding="utf-8"))
MemoryError

**Comment by d41k4n** [comment]
Not sure what causes this but there is also binary version for windows you might want to try out in order to see if that helps exclude any issues with missing/wrong Visual C++ redistributable libs:

https://drive.google.com/open?id=1PWgp33gDUQbY3uZmYbTi3ccMPLIJMQAQ

**Comment by Raurits** [comment]
Many thanks, d41k4n. The binary version does not have this problem for me.
