### ISSUE TITLE
No system list on Python 3.7 + Win10

### ISSUE THREAD

**Issue by gallart** [oscarpilote/Ortho4XP#52]
Hello,

Trying to run Ortho4XP under Win10 + Python 3.7.2.
Installed Pyproj 1.9.5.1 and 1.9.6 (cp37/amd64).

But still getting the same issue when running Ortho4XP 1.30 :

```
Traceback (most recent call last):
 File "Ortho4XP_v130.py", line 9, in <module>
   import O4_Imagery_Utils as IMG
 File ".\src\O4_Imagery_Utils.py", line 14, in <module>
   import O4_Geo_Utils as GEO
 File ".\src\O4_Geo_Utils.py", line 19, in <module>
   epsg['4326']=pyproj.Proj(init='epsg:4326')
 File "C:\Users\Gaëtan Allart\AppData\Local\Programs\Python\Python37\lib\site-packages\pyproj\__init__.py", line 362, in __new__
   return _proj.Proj.__new__(self, projstring)
 File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'no system list, errno: 2\n'
```

Thanks for your help

**Comment by oscarpilote** [comment]
You might wish to use the packaged version then (link can be found in my signature on x-plane.org forum), it does not require any user side install.
[Did you installed the packages from Christophe Gohlke's website ? That one is considered quite reliable]

**Comment by gdraps** [comment]
Ran into the same issue using Anaconda (python3.7), which installed pyproj version 1.9.6 by default.
Fixed this issue by installing a newer version with pip itself.
```
conda uninstall pyproj
pip install pyproj==2.4.0
```
