### ISSUE TITLE
'tmp' directory not created 

### ISSUE THREAD

**Issue by justyntemme** [oscarpilote/Ortho4XP#80]
After 
```
-> Loading of elevation data.
   No elevation file found, I download it from viewfinderpanorama (J. de Ferranti)
```

We get an error in the python file
```
Traceback (most recent call last):
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
  File "C:\Users\Oscar Pilote\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2753, in build_mesh
  File "D:\Ortho4XP\Ortho4XP_v120b.py", line 2156, in load_altitude_matrix
FileNotFoundError: [Errno 2] No such file or directory: '..\\tmp\\J14.zip'
```

This can be fixed by manually creating the tmp directory in the working folder.

**Comment by d41k4n** [comment]
Fixed in 1.30
